#!/bin/bash
#######################################################################
clear

allow_only_root() {
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer l'installation."; exit 1
  fi
}
allow_only_root

for f in ./ResPinGuy-CMD/respinguy \
          ./ResPinGuy-CMD/respinguy-app-rm \
          ./ResPinGuy-CMD/respinguy-app-up \
          ./ResPinGuy-CMD/respinguy-build \
          ./ResPinGuy-CMD/respinguy-config \
          ./ResPinGuy-CMD/respinguy-app-dep; do
    if [ ! -f "$f" ]; then echo "[ERREUR] Fichier manquant : $f"; exit 1; fi
done

read -p "Appuyez sur Entrée pour lancer l'installation..."

cp ./ResPinGuy-CMD/respinguy /usr/bin/         && chmod +x /usr/bin/respinguy         && echo "... [1/6]" || exit 1
cp ./ResPinGuy-CMD/respinguy-app-rm /usr/bin/  && chmod +x /usr/bin/respinguy-app-rm  && echo "... [2/6]" || exit 1
cp ./ResPinGuy-CMD/respinguy-app-up /usr/bin/  && chmod +x /usr/bin/respinguy-app-up  && echo "... [3/6]" || exit 1
cp ./ResPinGuy-CMD/respinguy-build /usr/bin/   && chmod +x /usr/bin/respinguy-build   && echo "... [4/6]" || exit 1
cp ./ResPinGuy-CMD/respinguy-config /usr/bin/  && chmod +x /usr/bin/respinguy-config  && echo "... [5/6]" || exit 1
cp ./ResPinGuy-CMD/respinguy-app-dep /usr/bin/ && chmod +x /usr/bin/respinguy-app-dep && echo "... [6/6]" || exit 1
echo "Les commandes sont installées."

cp -r ResPinGuy-File/ /usr/share/        && echo "... [1/2]" || exit 1
cp -r ResPinGuy-File-Config/ /usr/share/ && echo "... [2/2]" || exit 1
echo "Les fichiers sont installés."

clear
echo "Vérification des dépendances..."
bash /usr/share/ResPinGuy-File/respinguy-app-dep
if [ $? -ne 0 ]; then
    echo ""
    echo "[ATTENTION] Dépendances manquantes."
    echo "Utilisez : /usr/share/ResPinGuy-File/respinguy-app-dep-force-install"
else
    echo "---"
    echo "ResPinGuy est prêt. Lancez : respinguy"
    echo "---"
fi
