#!/bin/bash
#_____________________________________________________________________________________________
# Seul root peut continuer, car seul root peut lire tous les fichiers de votre système !
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1
  fi
}
allow_only_root
#_____________________________________________________________________________________________
echo "ResPinGuy - Créer des images de son système Linux"
echo "."
echo "- - -"
echo "."
echo "Commande :"
echo "."
echo "MAJ de ResPinGuy : respinguy-app-up"
echo "Configuration de ResPinGuy : respinguy-config"
echo "Création d'une Image ISO de son système : respinguy-build"
echo "Supprimer ResPinGuy de votre système : respinguy-app-rm"
echo "Verifier les dependances de ResPinGuy : respinguy-app-dep"
echo "Forcer l'installation des dependances de ResPinGuy : /usr/share/ResPinGuy-File/respinguy-app-dep-force-install"
echo "."
echo "ResPinGuy Officiel [®©]"