#!/bin/bash
allow_only_root() {
  if [ "0$UID" -ne 0 ]; then echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1; fi
}
allow_only_root
echo "ResPinGuy - Créer des images ISO de son système Linux"
echo "."
echo "- - -"
echo "."
echo "Commandes disponibles :"
echo "."
echo "  Aide                         : respinguy"
echo "  Configuration                : respinguy-config"
echo "  Créer une image ISO          : respinguy-build"
echo "  Mise à jour de ResPinGuy     : respinguy-app-up"
echo "  Supprimer ResPinGuy          : respinguy-app-rm"
echo "  Vérifier les dépendances     : respinguy-app-dep"
echo "  Forcer install dépendances   : respinguy-app-dep-force-install"
echo "."
echo "ResPinGuy Officiel [®©]"
