#!/bin/bash
allow_only_root() {
  if [ "0$UID" -ne 0 ]; then echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1; fi
}
allow_only_root

cd /usr/share/ResPinGuy-File-Config/ || exit 1
. ./respinguy-config || exit 1

bash /usr/share/ResPinGuy-File/respinguy-app-dep
if [ $? -ne 0 ]; then echo "[ERREUR] Dépendances manquantes. Build annulé."; exit 1; fi

if [ ! "$(dracut --list-modules | grep squash)" ]; then
  echo "[ERREUR] Module dracut manquant : squash (package : dracut-squash)"; exit 1
fi
if [ ! "$(dracut --list-modules | grep dmsquash-live)" ]; then
  echo "[ERREUR] Module dracut manquant : dmsquash-live (package : dracut-live)"; exit 1
fi
if [ ! -f "$VMLINUZ" ]; then
  echo "[ERREUR] Kernel introuvable : $VMLINUZ"; exit 1
fi
if [ -z "$RPGBUILDNAME" ] || [ -z "$RPGHOME" ] || [ -z "$KERNEL" ]; then
  echo "[ERREUR] Variable RPGBUILDNAME, RPGHOME ou KERNEL non définie dans respinguy-config"; exit 1
fi
if [ -n "$RPGCONFIGUSER" ] && [ -n "$RPGCONFIGUSERPERS" ]; then
  echo "[ERREUR] RPGCONFIGUSER et RPGCONFIGUSERPERS ne peuvent pas être définis en même temps."; exit 1
fi

clear
echo "_ _ _"
echo "Résumé avant création"
echo "---"
echo "Nom              : $RPGBUILDNAME"
echo "Kernel           : $VMLINUZ"
echo "Version kernel   : $KERNEL"
echo "Architecture     : $ARCH"
echo "Dossiers inclus  : $ROOTDIR"
echo "ISO de sortie    : $RPGHOME"
echo "Dossier de build : /respinguy-build-dir/"
if [ -n "$RPGCONFIGUSER" ]; then
  echo "Home utilisateur : $HOME (ISO uniquement)"
elif [ -n "$RPGCONFIGUSERPERS" ]; then
  echo "Home utilisateur : $HOME (ISO + persistance)"
else
  echo "Home utilisateur : non inclus"
fi
echo "_ _ _"
rm -rf /respinguy-build-dir/
read -p "Appuyez sur Entrée pour lancer le build..."

cd / || exit 1
mkdir -p /respinguy-build-dir/LiveOS

echo "Copie des fichiers ISO..."
cp -r /usr/share/ResPinGuy-File/fichier/iso/isolinux/ /respinguy-build-dir/
cp /usr/share/ResPinGuy-File-Config/bootimg.png /respinguy-build-dir/isolinux/
cp /usr/share/ResPinGuy-File-Config/isolinux.cfg /respinguy-build-dir/isolinux/

if [ -n "$RPGHOME" ] && [ "$RPGHOME" != "/" ]; then
  rm -rf "$RPGHOME" && mkdir -p "$RPGHOME"
else
  echo "[ERREUR] RPGHOME invalide : '$RPGHOME'"; exit 1
fi

echo "Copie du kernel..."
cp "$VMLINUZ" /respinguy-build-dir/vmlinuz

read -p "Appuyez sur Entrée pour continuer..."
clear

if [ -n "$RPGCONFIGUSER" ]; then
  bash /usr/share/ResPinGuy-File/script/rcu
elif [ -n "$RPGCONFIGUSERPERS" ]; then
  bash /usr/share/ResPinGuy-File/script/rcup
fi

echo "Création du squashfs..."
SQSFDIR=""
for i in $ROOTDIR; do
  [ -d "/$i" ] && SQSFDIR="$SQSFDIR /$i"
done
if [ -z "$SQSFDIR" ]; then echo "[ERREUR] Aucun dossier valide dans ROOTDIR."; exit 1; fi

mksquashfs $SQSFDIR /respinguy-build-dir/LiveOS/squashfs.img \
  -comp xz -b 1024K -always-use-fragments -keep-as-directory -noappend \
  -wildcards \
  -e "proc/*" "proc/.*" "run/*" "run/.*" "tmp/*" "tmp/.*" "sys/*" "sys/.*" \
  -e "var/crash/*" "root/.bash_history" "root/.cache" "root/.wget-hsts" \
  -e "home/*/.bash_history" "home/*/.cache" "home/*/.wget-hsts"

if [ $? -ne 0 ]; then echo "[ERREUR] Échec de la création du squashfs."; exit 1; fi
echo "Squashfs créé."
read -p "Appuyez sur Entrée pour continuer..."

if [ -n "$RPGCONFIGUSER" ]; then
  bash /usr/share/ResPinGuy-File/script/rcurm
fi

echo "Création de l'initrd..."
dracut -N -a dmsquash-live --kver "$KERNEL" /respinguy-build-dir/initrd --force
if [ $? -ne 0 ]; then echo "[ERREUR] Échec de la création de l'initrd."; exit 1; fi
echo "initrd créé."
read -p "Appuyez sur Entrée pour continuer..."

echo "Création de l'image ISO..."
cd / || exit 1
xorriso -as mkisofs \
  -r -J -joliet-long -l -iso-level 3 -cache-inodes \
  -isohybrid-mbr /usr/share/ResPinGuy-File/fichier/isohdpfx.bin \
  -partition_offset 16 -A "$RPGBUILDNAME" \
  -b isolinux/isolinux.bin -c isolinux/boot.cat \
  -no-emul-boot -boot-load-size 4 -boot-info-table \
  -o "$RPGHOME/$RPGBUILDNAME-$ARCH.iso" \
  /respinguy-build-dir/

if [ $? -ne 0 ]; then echo "[ERREUR] Échec de la création de l'ISO."; exit 1; fi
clear
echo "_ _ _"
echo "Build terminé ! ISO disponible dans : $RPGHOME/$RPGBUILDNAME-$ARCH.iso"
echo "_ _ _"
