#!/bin/bash
# ResPinGuy - Fichier de configuration
# Emplacement : /usr/share/ResPinGuy-File-Config/respinguy-config

# Nom de l'image ISO générée
RPGBUILDNAME="Respinguy-Custom"

# Dossier de destination de l'ISO final
RPGHOME=/home/ResPinGuy

# Répertoire home à inclure (décommentez et adaptez)
#HOME=/home/monuser/

# Option 1 : home dans l'ISO uniquement (sans persistance)
#RPGCONFIGUSER=1

# Option 2 : home dans l'ISO + persistance après install
#RPGCONFIGUSERPERS=1

# Emplacement du kernel (adapter selon la distro)
# Debian/Ubuntu : vmlinuz-$(uname -r)
# Fedora        : vmlinuz-$(uname -r)
# Arch          : vmlinuz-linux
VMLINUZ=/boot/vmlinuz-$(uname -r)

# Variables automatiques (ne pas modifier)
KERNEL=$(uname -r)
ARCH=$(uname -m)
ROOTDIR="bin boot etc home lib lib64 opt root sbin srv usr var"
