#!/bin/bash
allow_only_root() {
  if [ "0$UID" -ne 0 ]; then echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1; fi
}
allow_only_root
bash /usr/share/ResPinGuy-File-Config/respinguy-app-dep-force-install