#!/bin/bash
allow_only_root() {
  if [ "0$UID" -ne 0 ]; then echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1; fi
}
allow_only_root
cd /usr/share/ResPinGuy-File-Config/ || exit 1
. ./respinguy-config || exit 1
if [ -z "$HOME" ]; then echo "[ERREUR] HOME non défini dans respinguy-config."; exit 1; fi
rm -rf /etc/skel/*
cp -r "$HOME/." /etc/skel/
echo "[OK] $HOME copié dans /etc/skel/ (avec persistance)"
