#!/bin/bash
allow_only_root() {
  if [ "0$UID" -ne 0 ]; then echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1; fi
}
allow_only_root
if [ ! -d /etc/skel-save ]; then
  echo "[ERREUR] Aucune sauvegarde dans /etc/skel-save. Restauration impossible."; exit 1
fi
rm -rf /etc/skel/
mv /etc/skel-save/ /etc/skel/
echo "[OK] /etc/skel/ restauré."
